# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

 source 'https://github.com/ssamadgh/AOperationPod.git'


target 'Earthquakes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Earthquakes
  pod 'AOperation'


end
